Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "master" do |master|
    master.vm.network "private_network", type: "static", ip: "192.168.56.10"
    master.vm.hostname = "k8s-master"
    master.vm.provider "virtualbox" do |v|
      v.name = "k8s-master"
      v.memory = 4096
      v.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      echo 'vagrant:vagrant' | sudo chpasswd
      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart ssh
    SHELL
    master.vm.network "forwarded_port", guest: 5173, host: 5173
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.network "forwarded_port", guest: 5050, host: 5050
  end
end